services:
  - type: web
    name: portfolio-api
    runtime: node
    rootDir: server
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: CLOUDINARY_FOLDER
        value: portfolio
      - key: AUTH_SECRET
        sync: false
      - key: DEEPL_API_KEY
        value: "be17ceba-c3c5-4da5-9f84-13bba0c4c024:fx"
      - key: CORS_ORIGIN
        value: https://portfolio-caled-boukari.vercel.app
      - key: UPLOAD_MAX_FILE_SIZE
        value: "52428800"
